import type { Metadata } from 'next';
import '@radix-ui/themes/styles.css';
import { Sidebar } from '@/components/sidebar';
import { getUser } from '@/lib/auth';
import { redirect } from 'next/navigation';
import { getUserOrganizations } from '@/lib/db/queries';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { domain: string };
}>) {
  const { user } = await getUser();
  const userOrganizations = await getUserOrganizations(user?.id || '');
  const defaultUserOrgDomain = userOrganizations[0]?.domain;
  if (!userOrganizations.length) {
    redirect('/organization/search');
  } else if (!userOrganizations.find((org) => org.domain === params.domain)) {
    redirect(`/organization/${defaultUserOrgDomain}/overview`);
  }
  return (
    <>
      <Sidebar organizationDomain={params.domain} userOrganizations={userOrganizations} />
      {children}
    </>
  );
}
