import type { Metadata } from 'next';
import '@radix-ui/themes/styles.css';
import { Sidebar } from '@/components/sidebar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { slug: string };
}>) {
  return (
    <>
      <Sidebar organization={params.slug} />
      {children}
    </>
  );
}
