import type { Metadata } from 'next';
import '@radix-ui/themes/styles.css';
import { Sidebar } from '@/components/sidebar';
import { getUser } from '@/lib/auth';
import { db } from '@/lib/db/connection';
import { usersToOrganizations } from '@/lib/db/schema';
import { eq } from 'drizzle-orm';
import { redirect } from 'next/navigation';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { slug: string };
}>) {
  const { user } = await getUser();
  const userOrganizations = await db
    .select({ orgId: usersToOrganizations.orgId })
    .from(usersToOrganizations)
    .where(eq(usersToOrganizations.userId, user!.id));
  if (!userOrganizations.length) {
    redirect('/organization/search');
  }
  return (
    <>
      <Sidebar organization={params.slug} />
      {children}
    </>
  );
}
